### PR TITLE
Use correct php tags

### PR DESCRIPTION
**Pull request by liedekef**
Short php opening tags have long been deprecated.

### CODE REVIEW

**Comment by rikterbeek** [comment]
Hi Liesdekef,

That is not true see:

short_open_tag boolean
Tells PHP whether the short form (<? ?>) of PHP's open tag should be allowed. If you want to use PHP in combination with XML, you can disable this option in order to use <?xml ?> inline. Otherwise, you can print it with PHP, for example: <?php echo '<?xml version="1.0"?>'; ?>. Also, if disabled, you must use the long form of the PHP open tag (<?php ?>).

Note:
This directive also affected the shorthand <?= before PHP 5.4.0, which is identical to <? echo. Use of this shortcut required short_open_tag to be on. Since PHP 5.4.0, <?= is always available.

More information can be found here:
http://php.net/manual/en/ini.core.php#ini.short-open-tag

You can always use <?php if this works better for you.

Regards,
Rik

**Comment by liedekef** [comment]
Hi,

I'm not saying that the short tags are not possible anymore, just that it is no longer recommended to use them. No new installation of php comes with short tags enabled, and people taking over this code would thus have issues. See also: http://php.net/manual/en/language.basic-syntax.phptags.php

Franky

**Comment by RamonSmit** [comment]
:+1:

**Comment by rikterbeek** [comment]
Hi @RamonSmit and @liedekef,

information about this is different on php.net. To support older versions of php i will accept the pull request.

Regards,
Rik
Adyen

**Comment by RamonSmit** [comment]
Created #12 with new PR, which you can merge directly :smile:

**Pull request closed without merging**
